### ISSUE TITLE
Allow specifying different amount of row and column units

### ISSUE THREAD

**Issue by 1000nettles** [dmnsgn/perspective-grid#2]
Hey! This project is a huge help for me, thank you! I was wondering if it'd be possible to add a feature to specify the amount of units horizontally (rows) to be different than the amount of vertically (columns)? I have some use cases that are not just squares.

Thanks again. :)

**Comment by 1000nettles** [comment]
Alternatively, I'd be happy to build this feature in and open a PR. Not sure how you want folks contributing to this repo.

**Comment by dmnsgn** [comment]
Hi! This sounds like a good feature so PR definitely welcome. The codebase is not so fresh for me but I'd say changing  `gridUnitCount` to an array would be where to start, checking the dx/dy and see if the line equations still make sense:

https://github.com/dmnsgn/perspective-grid/blob/e887e77da7f77811d619a2c15a4d623c7316e88a/src/PerspectiveGrid.js#L26

In case you have any doubt on the best way to contribute, I have setup some contributing guidelines here:
https://github.com/dmnsgn/.github/blob/main/CONTRIBUTING.md

Thanks!

**Comment by 1000nettles** [comment]
Closing this.
